database:
  type: sqlite
  sqlite:
    file: "factions.sqlite"
  mysql:
    host: localhost
    username: root
    password: ""
    schema: "piggyfactions"
  worker-limit: 1

economy:
  enabled: false
  provider: economyapi
  faction-bank:
    enabled: false

factions:
  enforce-alphanumeric-names: false
  blacklisted-names:
    - staff
    - owner
    - osforce
    - OsForce
    - Osf
    - Shop
    - kontol
    - ngentod
    - kntl
    - ngtd
    - anjing
    - admin
    - mojang
  max-name-length: 16
  max-players: 15
  pvp:
    factionless: true
    between-factionless: true
  power:
    default: 0
    min: 0
    max: 10
    per:
      death: -2
      kill: 1
      hour: 2
  homes:
    within-territory: true
    teleport-on-death: true
  claims:
    blacklisted-worlds: []
    denied-commands:
      enemy:
        - home
        - spawn
        - Lobby
        - mines
        - PVP
        - hub
      none: []
      truce: []
      ally: []
    cost: 1
    max: -1
    shield-factor: 0.1
    overclaim: true
    autoclaim: true
    unclaimall: true
    circle:
      enabled: true
      max-radius: 15
    square:
      enabled: true
      max-radius: 15

languages:
  default: "english"

symbols:
  colors:
    relations:
      member: "{GREEN}"
      ally: "{DARK_PURPLE}"
      truce: "{LIGHT_PURPLE}"
      neutral: "{WHITE}"
      enemy: "{RED}"
      safezone: "{GOLD}"
      warzone: "{DARK_RED}"
  ranks:
    leader: "^"
    officer: "*"
    member: "+"
    recruit: "-"
    none: ""
  factionless: ""
  powerless: "0"

commands:
  disabled: []

forms: true
